<?php

use Illuminate\Database\Seeder;
class wordsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $data =array(
            array('category_id' => '1' ,'name' => 'Vaca'), 
            array('category_id' => '1' ,'name' => 'Ornitorrinco'), 
            array('category_id' => '1' ,'name' => 'Pato'), 
            array('category_id' => '1' ,'name' => 'Toro'), 
            array('category_id' => '1' ,'name' => 'Rinoceronte'), 
            array('category_id' => '1' ,'name' => 'Hipopótamo'), 
            array('category_id' => '1' ,'name' => 'Jirafa'), 
            array('category_id' => '1' ,'name' => 'Renacuajo'), 
            array('category_id' => '1' ,'name' => 'Cucaracha'), 
            array('category_id' => '1' ,'name' => 'Hormiga'), 
            array('category_id' => '1' ,'name' => 'Gusano'), 
            array('category_id' => '1' ,'name' => 'Estrella de mar'), 
            array('category_id' => '1' ,'name' => 'Caballo de mar'), 
            array('category_id' => '1' ,'name' => 'Caballo salvaje'), 
            array('category_id' => '1' ,'name' => 'Caballo'), 
            array('category_id' => '1' ,'name' => 'Lobo'), 
            array('category_id' => '1' ,'name' => 'Zebra'), 
            array('category_id' => '1' ,'name' => 'Pony'), 
            array('category_id' => '1' ,'name' => 'Yegua'), 
            array('category_id' => '1' ,'name' => 'Zorro'), 
            array('category_id' => '1' ,'name' => 'Conejo'), 
            array('category_id' => '1' ,'name' => 'Leopardo'), 
            array('category_id' => '1' ,'name' => 'Elefante'), 
            array('category_id' => '1' ,'name' => 'Chimpancé'), 
            array('category_id' => '1' ,'name' => 'Gorila'), 
            array('category_id' => '1' ,'name' => 'Cocodrilo'), 
            array('category_id' => '1' ,'name' => 'Ratón'), 
            array('category_id' => '1' ,'name' => 'Mariposa'), 
            array('category_id' => '1' ,'name' => 'Paloma'), 
            array('category_id' => '1' ,'name' => 'León'), 
            array('category_id' => '1' ,'name' => 'Tigre'), 
            array('category_id' => '1' ,'name' => 'Kanguro'), 
            array('category_id' => '1' ,'name' => 'Koala'), 
            array('category_id' => '1' ,'name' => 'Avestruz'), 
            array('category_id' => '1' ,'name' => 'Oso panda'), 
            array('category_id' => '1' ,'name' => 'Ciervo'), 
            array('category_id' => '1' ,'name' => 'Cabra'), 
            array('category_id' => '1' ,'name' => 'Oveja'), 
            array('category_id' => '1' ,'name' => 'Cerdo'), 
            array('category_id' => '1' ,'name' => 'Gallina'), 
            array('category_id' => '1' ,'name' => 'Ardilla'), 
            array('category_id' => '1' ,'name' => 'Gato'), 
            array('category_id' => '1' ,'name' => 'Perro'), 



            array('category_id' => '2' ,'name' => 'Vaporeon'), 
            array('category_id' => '2' ,'name' => 'Eevee'), 
            array('category_id' => '2' ,'name' => 'Tauros'), 
            array('category_id' => '2' ,'name' => 'Pikachu'), 
            array('category_id' => '2' ,'name' => 'Snorlax'), 
            array('category_id' => '2' ,'name' => 'Squirtle'), 
            array('category_id' => '2' ,'name' => 'Staryu'), 
            array('category_id' => '2' ,'name' => 'Pidgey'), 
            array('category_id' => '2' ,'name' => 'Magikarp'), 
            array('category_id' => '2' ,'name' => 'Charmander'), 
            array('category_id' => '2' ,'name' => 'Weedle'), 
            array('category_id' => '2' ,'name' => 'Clefairy'), 
            array('category_id' => '2' ,'name' => 'Jigglypuff'), 
            array('category_id' => '2' ,'name' => 'Psyduck'), 
            array('category_id' => '2' ,'name' => 'Tentacool'), 
            array('category_id' => '2' ,'name' => 'Poliwag'), 
            array('category_id' => '2' ,'name' => 'Caterpie'), 
            array('category_id' => '2' ,'name' => 'Seaking'), 
            array('category_id' => '2' ,'name' => 'Nidoran'), 
            array('category_id' => '2' ,'name' => 'Zubat'), 
            array('category_id' => '2' ,'name' => 'Spearow'), 
            array('category_id' => '2' ,'name' => 'Magmar'), 
            array('category_id' => '2' ,'name' => 'Persian'), 
            array('category_id' => '2' ,'name' => 'Ekans'), 
            array('category_id' => '2' ,'name' => 'Bulbassaur'), 
            array('category_id' => '2' ,'name' => 'Goldeen'), 
            array('category_id' => '2' ,'name' => 'Seel'), 
            array('category_id' => '2' ,'name' => 'Rattata'), 
            array('category_id' => '2' ,'name' => 'Meowth'), 
            array('category_id' => '2' ,'name' => 'Dratini'), 
            array('category_id' => '2' ,'name' => 'Sandshrew'), 
            array('category_id' => '2' ,'name' => 'Diglett'),


            array('category_id' => '3' ,'name' => 'Pizza'),
            array('category_id' => '3' ,'name' => 'Hamburguesa'),
            array('category_id' => '3' ,'name' => 'Hot dog'),
            array('category_id' => '3' ,'name' => 'Papas fritas'),
            array('category_id' => '3' ,'name' => 'Sopa'),
            array('category_id' => '3' ,'name' => 'Arroz'),
            array('category_id' => '3' ,'name' => 'Arroz chino'),
            array('category_id' => '3' ,'name' => 'Pollo frito'),
            array('category_id' => '3' ,'name' => 'Arepa'),
            array('category_id' => '3' ,'name' => 'Ensalada '),
            array('category_id' => '3' ,'name' => 'Tacos'),
            array('category_id' => '3' ,'name' => 'Nachos '),
            array('category_id' => '3' ,'name' => 'Espagueti '),
            array('category_id' => '3' ,'name' => 'Lasagna'),
            array('category_id' => '3' ,'name' => 'Pescado '),
            array('category_id' => '3' ,'name' => 'Pancakes '),
            array('category_id' => '3' ,'name' => 'Quesadillas '),
            array('category_id' => '3' ,'name' => 'Paella '),
            array('category_id' => '3' ,'name' => 'Camarones'),
            array('category_id' => '3' ,'name' => 'Carne molida'),
            array('category_id' => '3' ,'name' => 'Baby beef'),
            array('category_id' => '3' ,'name' => 'Carne llanera'),
            array('category_id' => '3' ,'name' => 'Frijoles'),
            array('category_id' => '3' ,'name' => 'Huevo '),
            array('category_id' => '3' ,'name' => 'Salchichas'),
            array('category_id' => '3' ,'name' => 'Carnes frías'),
            array('category_id' => '3' ,'name' => 'Carnes rojas'),
            array('category_id' => '3' ,'name' => 'Pudín '),
            array('category_id' => '3' ,'name' => 'Tiramuzú'),
            array('category_id' => '3' ,'name' => 'Galletas'),
            array('category_id' => '3' ,'name' => 'Pastel '),
            array('category_id' => '3' ,'name' => 'Cupcake'),
            array('category_id' => '3' ,'name' => 'Gelatina'),
            array('category_id' => '3' ,'name' => 'Tres leches'),
            array('category_id' => '3' ,'name' => 'Chocolate'),
            array('category_id' => '3' ,'name' => 'Cheesecake'),
            array('category_id' => '3' ,'name' => 'Ensalada de frutas'),
            array('category_id' => '3' ,'name' => 'Helado'),
            array('category_id' => '3' ,'name' => 'Pie'),
            array('category_id' => '3' ,'name' => 'Marialuisa'),


            array('category_id' => '4' ,'name' => 'Bogotá'), 
            array('category_id' => '4' ,'name' => 'Medellín'), 
            array('category_id' => '4' ,'name' => 'Cali'), 
            array('category_id' => '4' ,'name' => 'Barranquilla'), 
            array('category_id' => '4' ,'name' => 'Washington'), 
            array('category_id' => '4' ,'name' => 'Texas'), 
            array('category_id' => '4' ,'name' => 'Nueva Delhi'), 
            array('category_id' => '4' ,'name' => 'Estambul'), 
            array('category_id' => '4' ,'name' => 'Ankara'), 
            array('category_id' => '4' ,'name' => 'Sydney'), 
            array('category_id' => '4' ,'name' => 'Canberra'), 
            array('category_id' => '4' ,'name' => 'Lima'), 
            array('category_id' => '4' ,'name' => 'La Paz'), 
            array('category_id' => '4' ,'name' => 'Madrid'), 
            array('category_id' => '4' ,'name' => 'Barcelona'), 
            array('category_id' => '4' ,'name' => 'Londres'), 
            array('category_id' => '4' ,'name' => 'Toronto'), 
            array('category_id' => '4' ,'name' => 'Atenas'), 
            array('category_id' => '4' ,'name' => 'Rio de Janeiro'), 
            array('category_id' => '4' ,'name' => 'Sao Paulo'), 
            array('category_id' => '4' ,'name' => 'París'), 
            array('category_id' => '4' ,'name' => 'Venecia'), 
            array('category_id' => '4' ,'name' => 'Florencia'), 
            array('category_id' => '4' ,'name' => 'La Habana'), 
            array('category_id' => '4' ,'name' => 'Tokio'), 
            array('category_id' => '4' ,'name' => 'Jerusalén'), 
            array('category_id' => '4' ,'name' => 'Tel Aviv'), 
            array('category_id' => '4' ,'name' => 'Granada'), 
            array('category_id' => '4' ,'name' => 'Lisboa'), 
            array('category_id' => '4' ,'name' => 'Ámsterdam'), 
            array('category_id' => '4' ,'name' => 'Luxor'), 
            array('category_id' => '4' ,'name' => 'Berlin'), 
            array('category_id' => '4' ,'name' => 'Viena'), 
            array('category_id' => '4' ,'name' => 'Cuzco'), 
            array('category_id' => '4' ,'name' => 'Cartagena'), 
            array('category_id' => '4' ,'name' => 'Las Vegas'), 
            array('category_id' => '4' ,'name' => 'Praga'), 
            array('category_id' => '4' ,'name' => 'Budapest'), 
            array('category_id' => '4' ,'name' => 'Nueva York'), 
            array('category_id' => '4' ,'name' => 'Buenos Aires'), 
            array('category_id' => '4' ,'name' => 'Ottawa'), 
            array('category_id' => '4' ,'name' => 'Quebec'), 
            array('category_id' => '4' ,'name' => 'Moscú'), 


            array('category_id' => '5' ,'name' => 'Fresa'),
            array('category_id' => '5' ,'name' => 'Pera'),
            array('category_id' => '5' ,'name' => 'Maracuyá'),
            array('category_id' => '5' ,'name' => 'Mango'),
            array('category_id' => '5' ,'name' => 'Mora'),
            array('category_id' => '5' ,'name' => 'Kiwi'),
            array('category_id' => '5' ,'name' => 'Banano'),
            array('category_id' => '5' ,'name' => 'Uva'),
            array('category_id' => '5' ,'name' => 'Papaya'),
            array('category_id' => '5' ,'name' => 'Naranja'),
            array('category_id' => '5' ,'name' => 'Mandarina'),
            array('category_id' => '5' ,'name' => 'Melocotón'),
            array('category_id' => '5' ,'name' => 'Durazno'),
            array('category_id' => '5' ,'name' => 'Zapote'),
            array('category_id' => '5' ,'name' => 'Zanahoria'),
            array('category_id' => '5' ,'name' => 'Lechuga'),
            array('category_id' => '5' ,'name' => 'Tomate'),
            array('category_id' => '5' ,'name' => 'Papa'),
            array('category_id' => '5' ,'name' => 'Yuca'),
            array('category_id' => '5' ,'name' => 'Aguacate'),
            array('category_id' => '5' ,'name' => 'Lulo'),
            array('category_id' => '5' ,'name' => 'Limón'),
            array('category_id' => '5' ,'name' => 'Habichuela'),
            array('category_id' => '5' ,'name' => 'Remolacha'),
            array('category_id' => '5' ,'name' => 'Ajo'),
            array('category_id' => '5' ,'name' => 'Cebolla'),
            array('category_id' => '5' ,'name' => 'Berenjena'),
            array('category_id' => '5' ,'name' => 'Brócoli'),
            array('category_id' => '5' ,'name' => 'Calabaza'),
            array('category_id' => '5' ,'name' => 'Pepino'),
            array('category_id' => '5' ,'name' => 'Ciruela'),
            array('category_id' => '5' ,'name' => 'Cereza'),
            array('category_id' => '5' ,'name' => 'Mora azul'),

        );

	    \DB::table('words')->insert($data);
    }
}